// ye file poore app ko common structure provide krta h jese navbar , footer, etc. and is rendered in every page
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";

// Avail the fonts to use within app, not applied in here but in global css. It can also be directly aplied by removing variable from here and use geistSans.className in html > className
const geistSans = Geist({
  variable: "--font-geist-sans", // <--- creating CSS variable which can be used earlier in css as font-family: var(--font-geist-sans);
  subsets: ["latin"], // <--- sirf latin fonts (A,B,C,1,2,3..) load honge for speed instead of loading whole font
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Website k baare me info
export const metadata: Metadata = {
  title: "Next Playground", // <-- browser title
  description: "Generated by create next app", // <-- useful for search engines, description is displayed in google search via this
};

// every page renders inside this function, children is actual page content
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Layout preserves state and persists Header and Footer so that they don't re-render when switching pages  */}
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
